CREATE TABLE MOVIES 
(
  MID NUMBER NOT NULL 
, TITLE VARCHAR(255) 
, YEAR NUMBER(4) 
, RATING FLOAT  
, NUM_RATING NUMBER 
, CONSTRAINT MOVIES_PK PRIMARY KEY 
  (
    MID 
  )
);

CREATE TABLE ACTORS 
(
  MID NUMBER NOT NULL 
, NAME VARCHAR(255) DEFAULT 'UNKNOWN' NOT NULL  
, CAST_POSITION VARCHAR(255) 
, CONSTRAINT ACTORS_PK PRIMARY KEY 
  (
    MID 
  , NAME 
  )
 , CONSTRAINT MOVIES_FK FOREIGN KEY (MID) REFERENCES MOVIES(MID)
  ENABLE 
);

CREATE TABLE GENRES 
(
  MID NUMBER NOT NULL 
, GENRE VARCHAR(255) NOT NULL 
, CONSTRAINT GENRES_PK PRIMARY KEY 
  (
    MID 
  , GENRE 
  )
,CONSTRAINT GENRES_MOVIES_FK FOREIGN KEY (MID) REFERENCES MOVIES(MID)
  ENABLE 
);


CREATE TABLE TAG_NAMES 
(
  TID NUMBER NOT NULL 
, TAG VARCHAR(255) 
, CONSTRAINT TAG_NAMES_PK PRIMARY KEY 
  (
    TID 
  )
  ENABLE 
);



CREATE TABLE TAGS 
(
  MID NUMBER NOT NULL 
, TID NUMBER NOT NULL 
, CONSTRAINT TAGS_PK PRIMARY KEY 
  (
    MID 
  , TID 
  )
,CONSTRAINT TAG_MOVIES_FK FOREIGN KEY (MID) REFERENCES MOVIES(MID)
,CONSTRAINT TAG_TAGNAMES_FK FOREIGN KEY (TID) REFERENCES TAG_NAMES(TID)
  ENABLE 
);


